language: cpp
compiler:
 - gcc

install:
 - wget http://tfi.io/1t6nEa8
 - ls -alF
 - tar -xvf 1t6nEa8
 - sudo mv arduino-1.5.8 /usr/local/share/arduino
 - sudo apt-get install aptitude
 - sudo aptitude update && sudo aptitude -y install ia32-libs
 - git clone -b ide1.5x https://github.com/justonia/ino.git
 - cd ino && sudo make install && cd ../
 - sudo pip install jinja2
 - sudo pip install pyserial
 - pwd

script:
 - ino --help
 - file /usr/local/share/arduino/hardware/tools/g++_arm_none_eabi/bin
 - ls -alF /usr/local/share/arduino/hardware/tools/g++_arm_none_eabi/bin
 - /usr/local/share/arduino/hardware/tools/g++_arm_none_eabi/bin/arm-none-eabi-gcc --version
 - ino build